package com.ec.akirafinanzas.model.enums;

public enum typeMovementEnum {
    INGRESO, // INGRESOS DE DINERO A LAS CUENTAS
    EGRESO, // SALIDAS DE DINERO DE LAS CUENTAS
    TRANSFERENCIA, // MOVIMIENTOS ENTRE CUENTAS
    CARGO, // CARGOS O TARIFAS A LA CUENTA
    ABONO, // ABONOS O PAGOS A DEUDAS
    DEVOLUCION, // DEVOLUCIÓN DE DINERO A LA CUENTA
    INTERESES, // INTERESES GENERADOS
    AJUSTE, // AJUSTE DE SALDO
    PAGO // PAGO DE PRODUCTOS O SERVICIOS
}
